services:
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx-8.4-symfony-project
    restart: always
    ports:
      - ${PUBLISHER_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/:/etc/nginx/conf.d/
      - ./symfony-app:/var/www/html/
    depends_on:
      - php-fpm
    links:
      - php-fpm
    networks:
      - symfony-project

  php-fpm:
    image: jose-modified/php-fpm:8.4
    container_name: fpm-8.4-symfony-project
    restart: unless-stopped
    environment:
      - "ENV_SUBSTITUTION_ENABLE=true"
      - "PHP_MEMORY_LIMIT=1024M"
      - "PHP_FPM_LISTEN=9002"
      - "PHP_SESSION_GC_MAXLIFETIME=7200"
      - "PHP_DISABLE_EXTENSIONS=psr"
#       - "PHP_IDE_CONFIG: serverName=Docker"
    # expose:
    #   - "9003"
    volumes:
      - ./symfony-app:/var/www/html/
#       - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - symfony-project
      # - amqp_net
      - db_net_psql17
      # - redis_net

  # redis_publisher_db:
  #   image: redis:7.2-alpine3.18
  #   container_name: redis-publisher
  #   ports:
  #       - "6381:6379"
  #   volumes:
  #       - redis_publisher_data:/data
  #   restart: unless-stopped
  #   networks:
  #       - redis_net


# volumes:
#   redis_publisher_data:
networks:
  # amqp_net:
  #   name: amqp_net
  #   external: true
  symfony-project:
    name: symfony-project
    # external: true
  db_net_psql17:
    name: db_net_psql17
    external: true
  # redis_net:
  #   name: redis_net

